### ISSUE TITLE
Style CI

### ISSUE THREAD

**Issue by michaeltintiuc** [chrishalbert/laravel-nomadic#3]
I believe you'd still have to hook your repo to StyleCI in order to enable it, badges are also available ;)

**Comment by chalbert-edr** [comment]
I'll have to pull that out then. I exclude tests from the chadicus/coding-standards since they are relatively strict, but I suppose I can include them - and for free

**Comment by chrishalbert** [comment]
Removed in https://github.com/chrishalbert/laravel-nomadic/pull/5
